Make OutputModel aware of CUDA graph capturing.
torchmd/torchmd-net pull request #214
Opened 2023-09-18 13:55 UTC by RaulPPelaez

The reduction in OutputModel requires knowing the number of batches (computed as batch.max()+1) to be able to produce a tensor with a per-batch property (a.i. the total energy). 
This operation is inherently blocking and thus cannot be called during CUDA graph capture.
 
One way to go around this limitation is to make the OutputModel store the number of batches each time it is called.
Then, if the module is called in capture mode (which can be detected with `torch.cuda.is_current_stream_capturing()`) the previously stored value is used instead.
This makes it so that the number of batches of a captured model cannot be larger than the one used in the call previous to capture. However, this limitation is proper to CUDA graphs and thus I do not consider it an additional limitation.

This PR implements this strategy, warning the user about this when they capture the model and raising if the model is being called without warming up first.
Possible alternatives:
1. Adding a new parameter to TorchMD_Net (like n_batches). I think this is more error prone.
2. Computing  and storing batch.max()+1 during capture without including it into the graph. I do not think this is possible sadly.

2023-09-18 14:49 UTC, RaulPPelaez commented
Welp, I was not counting on this one...
```shell
Python builtin <built-in function _cuda_isCurrentStreamCapturing> is currently not supported in Torchscript:
```

2023-09-20 13:50 UTC, raimis commented
I have an idea how to circument this

2023-09-20 14:53 UTC, RaulPPelaez commented
As a matter of fact this does not use nvcc, I think everything required is in cudatoolkit!

2023-09-20 17:12 UTC, raimis commented on torchmdnet/models/output_modules.py
> +                self.dim_size == 0
Maybe
```python
self.dim_size > 0
```

2023-09-21 09:31 UTC, raimis commented on torchmdnet/models/output_modules.py
> +        verbose=True,
No need to be verbose

2023-09-21 09:46 UTC, raimis commented on torchmdnet/models/output_modules.py
> +        verbose=True,
OK!

2023-09-21 14:59 UTC, raimis requested changes
It works! For clarity, if you can move `check_stream_capturing` to a separate file, this is ready to be merged.

2023-09-22 14:27 UTC, RaulPPelaez commented
@raimis please review again so I can merge

2023-09-22 14:35 UTC, raimis approved these changes

2023-09-22 14:36 UTC, merged