Update installation instructions regarding CUDA
torchmd/torchmd-net pull request #250
Opened 2024-01-09 15:32 UTC by RaulPPelaez

cc @peastman 
Follow up from #249

2024-01-09 17:24 UTC, peastman commented
I would rather have it install CUDA 12 versions of everything.  I tried

```
CONDA_OVERRIDE_CUDA="12" mamba env create -f environment.yml
```

but it still installs 11.8.  I'm not sure where it's getting that from.  Presumably it must be required by one of the dependencies listed in environment.yaml?  The computer has a very recent driver and CUDA 12.2.

2024-01-10 08:37 UTC, RaulPPelaez commented
Trying to get to the bottom of this here: https://github.com/conda-forge/cuda-version-feedstock/issues/14

2024-01-16 10:28 UTC, sef43 requested changes

2024-01-16 10:28 UTC, sef43 commented on docs/source/installation.rst
the rst markup formatting is not quite correct on this file. At least looking at the version rendered by github: https://github.com/RaulPPelaez/torchmd-net/blob/docs_update/docs/source/installation.rst

2024-01-16 10:28 UTC, sef43 commented on README.md
can we just link to the installation.rst file instead of duplicating error prone instructions?

2024-01-16 11:20 UTC, RaulPPelaez commented on README.md
I agree!

2024-01-16 11:22 UTC, RaulPPelaez commented
I have not gotten a response yet from mamba guys. Perhaps the way to go here is not recommend mamba for the "from source" installation instructions.

2024-01-16 11:28 UTC, sef43 commented
Alternatively we just point people to the CUDA docs and tell them to install nvcc + extra from the official NVIDIA channels?
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#conda-installation
Making a full nvcc compiler setup from conda is good for CI and deployment but not ideal for a user who probably already has a working nvcc on their system

2024-01-16 11:35 UTC, RaulPPelaez commented
Well, official instructions include installing using conda from the nvidia channel. The other ones normally require root access, which I do not like given how we manage to get all the rest of the dependencies without it.
It is true though that in the end the target machine requires the correct driver anyway, so might as well get CUDA in the process. Let me give it a try and see if I can put everything in there...

2024-01-16 11:59 UTC, sef43 commented
The latest conda install commands work for me for cuda 12

2024-01-16 13:31 UTC, RaulPPelaez commented
I am going to merge this.

2024-01-16 13:32 UTC, merged

2024-01-16 20:04 UTC, peastman commented
I'm trying to follow the instructions in this PR.  Conda has been running for about an hour trying to solve the environment for the `conda env create` command. :(

2024-01-16 20:44 UTC, sef43 commented
Note that new and up to date conda will actually use libmamba solver backend. So for me the conda install was just as fast as the mamba one. But then I don't know if the original mamba bug in this issue still occurs.

https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/

2024-01-16 21:17 UTC, peastman commented
So it might be faster but have the same problem as mamba...  How useful!

It did finally succeed, and it installed CUDA 12.0.  It's now working on the command to install the rest of the CUDA libraries.

2024-01-16 22:25 UTC, peastman commented
Everything eventually succeeded and I now have a working install.  It just took patience.  Thanks!